ZFS: ZFSLinebyline Class Reference
ZFSLinebyline Class Reference
Basic class for lineByline access.
Public Types
enum { PDATA_GET_XYZ = (1<<0) , PDATA_GET_MASK = (1 << 1) , PDATA_GET_POST = (1 << 2) , PDATA_GET_EVERYTHING = 0xffff }
return the whole line already calculated (fasted access of line)
typedef std::pair< int32_t, int32_t > pxln
typedef std::vector< ZFBase * > objlist_t
typedef void(* cbObj_t) (objlist_t &, bool)
typedef bool(* cbXYZ_f) (const ZFSLinebyline *, const ZFLineAccess *, const ZFBase *, int32_t u, int32_t v, double &x, double &y, double &z)
typedef void(* cbLine_f) (const ZFSLinebyline *, const ZFBase *, int32_t ln)
Public Member Functions
ZFTRMatrix & Matrix ()
const ZFTRMatrix & Matrix () const
ZFTRMatrix & LevelMatrix ()
const ZFTRMatrix & LevelMatrix () const
int32_t LevelMatrixStatus () const
double getMinRfPercent () const
int32_t RfPercentToRf (double rfPercent) const
const char * FileName ()
const wchar_t * FileNameW () const
bool HasRGB () const
bool LoadRGB (const std::wstring &imageFilename)
std::wstring fileNameColorPictureW () const
uint32_t getImageWidth () const
uint32_t getImageHeight () const
zfs::math::rgb rgb_col (bool &ok)
zfs::math::rgb rgb ()
get color of pixel of previous line, otherwise r,g,b has the same value
zfs::math::rgb rgb (const ZFLineAccess *l)
zfs::math::rgb rgb (const ZFLineAccess *l, zfs::PData &px)
virtual int32_t Typ () const
virtual zfs::zfserr_t Open (const std::wstring &, int32_t flags=0)
open a zfs scan
void Close ()
close
bool Ok () const
bool IsProfiler ()
return true if scan was taken in profilermode or scanner is a profiler
ZFSLinebyline * Clone ()
bool IsClone () const
bool Create (const std::wstring &, ZFSHeader *)
ZFLineAccess * GetLine ()
const ZFLineAccess * GetLine () const
ZFLineInfo * LineInfo ()
const ZFLineInfo * LineInfo () const
zfs::AtmosphereCorrection & atmosphereCorrection ()
zfs::RawParams & strayLight ()
const zfs::RawParams & strayLight () const
virtual void LoadCalibration ()
void UseLProfiler (bool use=true, double rotX=0., double rotY=0., double rotZ=0.)
void InitWay (zfs::way_t m=zfs::WAY_NO, double v=.01, bool helix=true)
int32_t WayMod () const
current way calculation mode
double CalcWay (int32_t line, double pixel=0.)
void WayModEnable (bool)
switch on / off calculation
bool IsWayModeEnabled () const
whether is enabled
double Way () const
double Way (ZFLineAccess *) const
bool IsCalibrated () const
const char * CalibInfo () const
const char * ModelInfo () const
int32_t SkipTo (int32_t line, bool reload=false)
virtual int32_t LoadLines (int32_t lines=1)
int32_t operator++ ()
int32_t LoadLineHeader (int32_t line, char *buf, int32_t bufsize)
get lineheader, random access posssible. does not read linedata itself. return number of bytes read, 0 if not successfull
int32_t LoadLineHeader (int32_t line, zfs::LineHeader &)
get lineheader, random access posssible. does not read linedata itself. return number of bytes read, 0 if not successfull
int32_t LoadLineHeader (int32_t line, zfs::LineHeaderBuf &)
get lineheader, random access posssible. does not read linedata itself. return number of bytes read, 0 if not successfull
int64_t determineFilePos (int32_t ln)
get file position return 0 if not possible
int64_t LoadRawLine (std::vector< char > &buf)
ZFSHeader * GetZFSHeader ()
const ZFSHeader * GetZFSHeader () const
ZFSHeader * GetCurrentZFSHeader ()
ZFSHeader * GetFirstZFSHeader ()
const ZFSHeader * GetFirstZFSHeader () const
int32_t Lines () const
int32_t LinesCurrentFile () const
int32_t Pixel () const
int32_t GetStartLine ()
int32_t GetLinesTo (int32_t fileNr)
bool HasLine () const
bool HasLinePre () const
bool HasLineNext () const
ZFLineAccess * L () const
ZFLineAccess * LPre () const
ZFLineAccess * LNext () const
int32_t MinRf () const
minimum usable intensity
int32_t MaxRf () const
maximum usable intensity
double MinRange () const
minimum range [meter]
double MaxRange () const
maximum range [meter]
const wchar_t * CurrentFileNameW ()
const char * CurrentFileName ()
bool Set (int32_t pix, int32_t l=0)
int32_t CurrentPixel () const
int32_t CurrentLine () const
int32_t LineInCurrentPart () const
virtual bool isZero () const
checks rf and rg for zero
int32_t Rf (ZFLineAccess *l=nullptr) const
double RfNorm () const
double RfNorm1 () const
bool isRfNormValid () const
double Rgm (ZFLineAccess *l=nullptr) const
void getPData (ZFLineAccess *, zfs::PDatas< zfs::PDataRaw > &line)
void getPData (ZFLineAccess *, zfs::PDatas< zfs::PDataDetail > &line, int get=PDATA_GET_EVERYTHING)
void Angle (double &h, double &l) const
std::pair< double, double > Angle () const
void Angle (double range, double &h, double &l) const
void AngleUncal (double &h, double &l)
void AngleUncal (double rgm, double &h, double &l)
bool physical2image (const pxln orginal, pxln &transfered) const
replacement for Map
bool image2physical (const pxln orginal, pxln &transfered) const
replacement for UnMap
bool Map (int32_t &p, int32_t &l) const
outdated, please use physical2image
bool UnMap (int32_t &p, int32_t &l) const
outdated, please use image2physical
ZFScanMap * MapObj ()
const ZFScanMap * MapObj () const
bool SetPreLine (int32_t pix)
int32_t PreRf ()
double PreRgm ()
bool SetNextLine (int32_t pix)
int32_t NextRf ()
double NextRgm ()
void SetRgm (double m)
void SetRf (int32_t inc)
int32_t Rgmm (ZFLineAccess *l=NULL) const
virtual void XYZ0 (double &x, double &y, double &z, const ZFLineAccess *l=NULL) const
virtual void PreXYZ0 (double &x, double &y, double &z)
zfs::math::Vec3d PreXYZ0 ()
virtual void NextXYZ0 (double &x, double &y, double &z)
zfs::math::Vec3d NextXYZ0 ()
void XYZ (double &x, double &y, double &z, const ZFLineAccess *l=nullptr) const
void PreXYZ (double &x, double &y, double &z)
void NextXYZ (double &x, double &y, double &z)
void Angle0 (double &henc_rad, double &lenc_rad)
void Angle0 (int32_t u, int32_t v, double &henc_rad, double &lenc_rad)
void XYZ0 (double henc, double lenc, double rg, double &x, double &y, double &z) const
zfs::math::Vec3d XYZ0 () const
zfs::math::Vec3d XYZ () const
bool SupportXYZ2POS () const
backtransformation from xyz too pixel and line if supported. return true if success scan has to be open with flag ..XYZ2POS
bool XYZ2POS (double x_local, double y_local, double z_local, double &pixel, double &line, bool forceScdLayer=false, bool forCal=false)
bool XYZ2POS (double x_local, double y_local, double z_local, int32_t &pixel, int32_t &line, bool forceScdLayer=false, bool forCal=false)
bool XYZ2POS (const zfs::math::Vec3d &xyz, int32_t &u, int32_t &v, bool secondLayer=false, bool forCal=false)
access via zfs::mat::Vec3d
bool Compensator (zfs::math::Vec3d &, const ZFLineAccess *l) const
XYZ0 with compensator correction.
bool Compensator (double &x, double &y, double &z, const ZFLineAccess *l) const
void FilterDefine (const ZFSFilter &param)
setup the params for filtering
void FilterDefine (const zfs::FilterParams &)
void usePreNextForFilter (bool use)
use 3-line filtering
bool PrepareFilter ()
Filter the line.
zfs::LineFilterResult Filter ()
zfs::LineFilterResult FilterForceOneLine ()
force to filter using just one line, ignoring re and next
int32_t Filter (uint32_t fromPixel, uint32_t toPixel)
Filter just a part of the line.
void ClearFilterResult ()
clear the filter result so next filter call on the same line will call the filter with maybe changed params again and create a new result
bool IsSet (int32_t x) const
Check if pixel is enabled or disabled by a filter.
bool attachLayer (const std::wstring &name=L"mask")
add a layer file to the scan
int hasLayerLoaded () const
/// check if a layer file was loaded. return number of layers (currently just one supported)
std::vector< std::pair< std::wstring, int > > layersLoaded () const
/// get a list of layers loaded on number of available in the parts
int isSetLayer (int line, int px) const
bool setLayer (int line, int px, int val, int layer=0)
/// set a new value to the layer. Need write access to layer. Open scan with option OPEN_RW
bool IsZeroPixel () const
double HOffset () const
checks whether pixel is a filled pixel at the end of a line (exist only in lara mode)
double LOffset () const
void SetHOffset (double o)
int32_t pixel360 () const
double MOffset () const
void SetMOffset (double o)
double MScale () const
void SetMScale (double s)
ZFSpline * PtrRfComp ()
not null if referenz correction available
const ZFSpline * PtrRfComp () const
not null if referenz correction available
bool HasRfComp () const
virtual double RefRg () const
referenz of current line (unit:meter) return 0 if not available
virtual double RefRf () const
referenz intensity of current line (unit:increments) return 0 if not available
void SetRgmm (int32_t mm)
const char * Info ()
void AddInfo (const char *inf)
bool WriteHeader ()
char getRgc () const
int32_t getParts () const
return number of parts
const std::vector< PartInf > * getPartList () const
return a list of all possible parts
int32_t getCurrentPart ()
return current part of scan
std::pair< int, int > getPartAndRellinenumber (int line_abs) const
bool WriteMask (int32_t aktLineFrom, int32_t aktLineTo)
bool WriteMask ()
bool AddMask (const std::wstring &name, zfs::math::rgb rgb={255, 0, 0})
bool AddMask (int32_t aktLineFrom, int32_t aktLineTo, zfs::math::rgb rgb, const std::wstring &name, bool set=true)
bool FindMask (const std::string &name) const
bool FindMask (const std::wstring &name) const
void parseMasks (std::function< void(ZFMask *) >)
ZFMaskPartial * findMask (int part, const std::wstring &mask_name)
bool RemoveMask (const std::string &name)
bool RemoveMask (const std::wstring &name)
std::vector< ZFMaskInfo > getMaskInfoList () const
int32_t IsSetCurrentMask (int32_t x)
bool IsSetMask (int32_t x) const
void SetMask (int32_t p, int32_t l, const std::wstring &name=L"")
void ClrMask (int32_t p, int32_t l, const std::wstring &name=L"")
bool HasMask () const
int ResetMask (const std::wstring &name)
reset/clear all masks with defined name in all parts. Retunr number of masks in parts reseted
ZFMaskPartial * maskOfPart (int part, const std::wstring &maskName)
ZFBase * addObj (ZFBase *)
Add new object.
bool removeObj (ZFBase *)
Remove the object.
void removeObjAll (const char *name=NULL)
Remove all objects. Use name to remove all objects of one typ.
void installXYZCallback (cbXYZ_f cb, ZFBase *o=NULL)
void installLineCallback (cbLine_f cb, ZFBase *o=NULL)
bool FastXYZ (bool fast)
Use fast xyz calculation for 5006 Profiler lara-sync (is used by default if possible)
bool IsFastXYZ () const
bool ErrVec (double &x, double &y, double &z)
bool writeCurrentLine ()
bool writwLineHeader ()
bool writwPreLineHeader ()
bool writeAllHeader (int32_t idx, int32_t value)
bool writeAllHeader (int32_t idx, double value)
void PostXYZ0Action (double &x, double &y, double &z, const ZFLineAccess *l) const
will be called automatically after XYZ0. Just internal usage
void PostXYZ0Action (zfs::math::Vec3d &, const ZFLineAccess *l) const
bool createSimulatedLines (ZFSHeader &)
just for unit test
Public Member Functions inherited from ZFBase
ZFBase (const ZFBase &other)
Custom copy constructor does not copy the locks, so an copied object will never be locked.
ZFBase & operator= (ZFBase other)
virtual const char * className () const
virtual bool isKindOf (const char *n) const
void AddLock (zfs::ZFLock *)
void ReleaseLock (zfs::ZFLock *)
bool IsLocked () const
void ResetLocks ()
int GetNumberOfLocks () const
void Kill ()
bool IsKilled () const
bool WaitKilled (int to=100)
Static Public Member Functions
static double getMinRfPercent (const ZFSHeader *h)
static int32_t RfPercentToRf (double rfPercent, const ZFSHeader *h)
Static Public Member Functions inherited from ZFBase
static const char * getClassName ()
Public Attributes
ZFReader * reader {}
zfs::zfs_flags_t flags {}
std::string info
Info about scan, ...
ZFSHeader * fileHeader {}
Pointer to current fileheader.
bool ok
Flag if access is ok.
ZFLineAccess * linePre {}
Line bevor current line in roll mode.
ZFLineAccess * zeile {}
Current line.
ZFLineAccess * lineNext {}
Line after current line. in roll mode.
ZFModel * model {}
3D Model class for xyz calculation
ZFTRMatrix matrix
World matrix.
int32_t levelMatrixStatus {}
ZFTRMatrix levelMatrix
Leveling system matrix if supported.
zfs::Compensator * compensator {}
int32_t openflags {}
File open flags.
int32_t typ {}
File typ.
ZFSFilter * mxpx {}
holds filtersettings
int32_t clones {}
ZFSLinebyline * cloneParent {}
ZFRf rf
mode for viewing image
ZFAngleToPixel * a2p {}
bool supportXYZ2POS = false
mode for viewing image
zf::FileName fileName
Name of the open .zfs file. (first name if scan exist of more files)
objlist_t objlist
Holds variable kind of objects assosiated with scan. Destructor frees objects.
ZFBase * cbObjXYZ {}
cbXYZ_f cbXYZ {}
ZFBase * cbObjLine {}
cbLine_f cbLine {}
Protected Member Functions
void FreeLines ()
bool DetectJpg ()
void DestroyJpg ()
zfs::zfserr_t DetectModel (bool checkImage=true)
bool Unahe ()
double RfComp () const
this will create a nice gray image but will take some time
double RfComp (ZFLineAccess *z) const
double RfComp1 (ZFLineAccess *z) const
Protected Attributes
ZFScanMap * pixLineMap {}
ZFLineInfo * lineInfo {}
ZFSpline * pRfComp {}
std::shared_ptr< zfs::TiledImage > image {}
bool mFilterPreNext {}
Protected Attributes inherited from ZFBase
ZFBase * pParentIfClone {}
Detailed Description
Basic class for lineByline access.
Member Enumeration Documentation
anonymous enum
anonymous enum
return the whole line already calculated (fasted access of line)
Range of Pixel unit=m
Member Function Documentation
Compensator()
bool ZFSLinebyline::Compensator (zfs::math::Vec3d & , const ZFLineAccess * l) const
XYZ0 with compensator correction.
Author
Susanne Lipkowski
Returns
bool
CurrentLine()
int32_t ZFSLinebyline::CurrentLine () const
current pixel
CurrentPixel()
int32_t ZFSLinebyline::CurrentPixel () const inline
Set pointer to pixel. Uses scan coordinates. l does nothing. Use SkipTo(l) instead
References ZFLineAccess::CurrentPixel(), and zeile.
FileName()
const char* ZFSLinebyline::FileName () inline
Returns the file name inclusive path
Filter()
int32_t ZFSLinebyline::Filter (uint32_t fromPixel, uint32_t toPixel)
Filter just a part of the line.
Returns
number of pixels masked out
GetCurrentZFSHeader()
ZFSHeader* ZFSLinebyline::GetCurrentZFSHeader ()
Returns a pointer to the first header. If file not open returns NULL
GetFirstZFSHeader()
ZFSHeader* ZFSLinebyline::GetFirstZFSHeader ()
Returns a pointer to the first header. If file not open returns NULL
GetLine()
ZFLineAccess* ZFSLinebyline::GetLine () inline
Returns a pointer to the current line.
GetLinesTo()
int32_t ZFSLinebyline::GetLinesTo (int32_t fileNr)
Returns the number of lines from the first file to the n file
getPartAndRellinenumber()
std::pair<int,int> ZFSLinebyline::getPartAndRellinenumber (int line_abs) const
get part and line in part having a absolute line number
Returns
part and rel-linenumber part=-1 if not found
GetStartLine()
int32_t ZFSLinebyline::GetStartLine ()
Returns number of startline of the current file
GetZFSHeader()
ZFSHeader* ZFSLinebyline::GetZFSHeader () inline
Returns a pointer to the header. If file not open returns NULL. Typically it is the header of the last part if there are severel parts
HasLine()
bool ZFSLinebyline::HasLine () const inline
Returns true if current line not null.
HasLineNext()
bool ZFSLinebyline::HasLineNext () const inline
Returns true if next line not null.
HasLinePre()
bool ZFSLinebyline::HasLinePre () const inline
Returns true if line before current line not null.
HasRGB()
bool ZFSLinebyline::HasRGB () const
Check if zfs Scan is a color scan
Returns
true if color is available
HOffset()
double ZFSLinebyline::HOffset () const inline
checks whether pixel is a filled pixel at the end of a line (exist only in lara mode)
Returns the offset for the height speed motor in rad.
Info()
const char* ZFSLinebyline::Info () inline
Returns the Information of the file as char string.
isRfNormValid()
bool ZFSLinebyline::isRfNormValid () const
Intensity as a float from 0.0 ... 1.0. Never use this value for filtering
isSetLayer()
int ZFSLinebyline::isSetLayer (int line, int px) const
check if layer is set. Layer has to be available and loaded with attachLayer return -1 if not available, 0 = valid pixel no layer 1..n bit set in layer n (inverted to meaning of the layer itself)
L()
ZFLineAccess* ZFSLinebyline::L () const inline
Returns a pointer to current line.
See also CurrentLine()
LineInCurrentPart()
int32_t ZFSLinebyline::LineInCurrentPart () const
current line of the total scan
LineInfo()
ZFLineInfo* ZFSLinebyline::LineInfo () inline
Returns a pointer to the line information class.
Lines()
int32_t ZFSLinebyline::Lines () const
Returns number of lines in scan.
LinesCurrentFile()
int32_t ZFSLinebyline::LinesCurrentFile () const
Returns number of lines in current file
LNext()
ZFLineAccess* ZFSLinebyline::LNext () const inline
Returns a pointer to next line.
LPre()
ZFLineAccess* ZFSLinebyline::LPre () const inline
Returns a pointer to line before current line.
MScale()
double ZFSLinebyline::MScale () const
Returns the scale range.
Ok()
bool ZFSLinebyline::Ok () const inline
Returns the zfs header acces status for the open file.
operator++()
int32_t ZFSLinebyline::operator++ () inline
Loads next line into memory.
See also LoadNextLine()
Returns
current line index
Pixel()
int32_t ZFSLinebyline::Pixel () const inline
Returns number of pixel of line.
PrepareFilter()
bool ZFSLinebyline::PrepareFilter ()
Filter the line.
Returns
number of pixels masked out will be called by Filter()
RefRf()
double ZFSLinebyline::RefRf () const inline virtual
referenz intensity of current line (unit:increments) return 0 if not available
return referenz intensity
References ZFLineAccess::RefRf(), and zeile.
RefRg()
double ZFSLinebyline::RefRg () const inline virtual
referenz of current line (unit:meter) return 0 if not available
return referenz range
References ZFLineAccess::RefRg(), and zeile.
RfNorm()
double ZFSLinebyline::RfNorm () const inline
real intensity from device
RfNorm1()
double ZFSLinebyline::RfNorm1 () const
Intensity as a float from 0.0 ... 1.0 for 100% but can be more than 100%. Never use this value for filtering
rgb()
zfs::math::rgb ZFSLinebyline::rgb ()
get color of pixel of previous line, otherwise r,g,b has the same value
get color of pixel, otherwise r,g,b has the same value
Rgmm()
int32_t ZFSLinebyline::Rgmm (ZFLineAccess * l = NULL) const
Returns the reflection of point p in current line. The pixel pointer in the line are set to p.
See also Rf()
Typ()
virtual int32_t ZFSLinebyline::Typ () const inline virtual
Returns the typ number of the scanner.
WriteHeader()
bool ZFSLinebyline::WriteHeader ()
Write changes in fileheader back to file
XYZ()
void ZFSLinebyline::XYZ (double & x, double & y, double & z, const ZFLineAccess * l = nullptr) const
Calculate form 2D pixel to 3D point for current pixel p. World XYZ.
See also
XYZ0(double& x, double& y, double& z)
Parameters
[out] x,y,z Coordinates of current pixel
l Line to load pixel from. If nullptr, use current line
XYZ0() [1/2]
virtual void ZFSLinebyline::XYZ0 (double & x, double & y, double & z, const ZFLineAccess * l = NULL) const virtual
unsafe, please do not use, use Rgm() instead
XYZ0() [2/2]
void ZFSLinebyline::XYZ0 (double henc, double lenc, double rg, double & x, double & y, double & z) const
X, y, z values without translation/rotation but with calibration (+compensator correction) if available.