#ifndef matrixerr_h
#define matrixerr_h

#include "Common/Err.h"

#define MATRIX_STATUS_OK                0
#define NON_44_INPUT_MATRIX         1
#define NON_44_OR_33_INPUT_MATRIX   2
#define NON_31_INPUT_MATRIX             3
#define DISPLAY_EMPTY_MATRIX            4
#define INVERSE_SINGULAR_MATRIX     5
#define TRACE_NOT_SQUARE_MATRIX     6
#define EXTRACT_TOO_BIG_MATRIX      7
#define INSERT_TOO_BIG_MATRIX           8
#define SETID_NOT_SQUARE_MATRIX     9
#define NORMALISE_NULL_MATRIX           10
#define NORMALISE_NON_VECTOR_MATRIX 11
#define AOP_DIFFERENT_SIZE_MATRIX   12
#define RANKDIAG_NON_COLUMN_MATRIX  13
#define INVDIAG_NON_COLUMN_MATRIX   14
#define CROSSP_WRONG_SIZE_MATRIX        15
#define INVHMAT_NON_44_INPUT_MATRIX 16
#define OPEQU_DIFFERENT_SIZE_MATRIX 17
#define OPD_DIFFERENT_SIZE_MATRIX   18
#define OPP_DIFFERENT_SIZE_MATRIX   19
#define OPMI_DIFFERENT_SIZE_MATRIX  20
#define OPMU_MISMATCH_SIZE_MATRIX   21
#define MATRIX_OPBR_OUT_OF_BOND     22
#define EQUA_DIFFERENT_SIZE_MATRIX  23
#define DIFF_DIFFERENT_SIZE_MATRIX  24
#define LUDINV_NON_SQUARE_MATRIX    25
#define LUDINV_SINGULAR_MATRIX      26
#define SVDINV_ILL_CONDIT_MATRIX    27
#define CHDINV_NON_SQUARE_MATRIX    28
#define CHDINV_SINGULAR_MATRIX      29
#define CHDINV_NON_SYMPOSDEF_MATRIX 30
#define MATRIX_ALLOCATION_FAILURE   31
#define LUDINV_SINGCLOSE_MATRIX     32
#define SVDINV_NON_SQUARE_MATRIX    33
#define GENNRP_ALLOC_FAIL_MATRIX    34
#define CHDINV_ALLOC_FAIL_MATRIX    35
#define SVDECM_ALLOC_FAIL_MATRIX    36
#define SVD_ALLOC_FAIL_MATRIX       37
#define LENGTH_NON_COLUMN_MATRIX    38
#define TOVECT_NON_COLUMN_MATRIX    39
#define DOTP_NON_COLUMN_MATRICES    40

extern ErrList matrixErr [];

#endif

