#ifndef ZFSFILTER_CONFIG_H
#define ZFSFILTER_CONFIG_H

//#define ZFSFILTER_STREULICHT
//#define ZFSFILTER_SKYFILTER
//#define ZFSFILTER_NONIUS
//#define ZFSFILTER_NONIUSJUMP
//#define ZFSFILTER_MIXPIX

#endif // ZFSFILTER_CONFIG_H
